### ISSUE TITLE
意见

### ISSUE THREAD

**Issue by macrobin** [ALEXTANGXIAO/GameNetty#3]
改的面目全非,目录结构全变了,以后升级都困难.

**Comment by yuliuren** [comment]
> 改的面目全非,目录结构全变了,以后升级都困难.

服务器目录结构跟原ET没有任何区别，客户端上核心结构依然跟ET一样。除了部分小文件的改动 。只是脱离了双端共享 。升级哪一步困难了?

**Comment by ALEXTANGXIAO** [comment]
核心结构基本一致，完全不存在升级困难的问题。反而原来为了共享双端、大量的Share、Client/Server的目录才是不合理。
