### ISSUE TITLE
客户端收不到M2C_StartSceneChange消息

### ISSUE THREAD

**Issue by shangdibaozi** [ALEXTANGXIAO/GameNetty#6]
在`EntryEvent1_InitShare.cs`中添加`root.SceneType = SceneType.Demo;`，以及修改`Init.cs`中`OnAppStartInitFinish`的`Attribute`，从`SceneType.Main`改为`SceneType.Demo`，客户端就可以正常收到消息了。

**Comment by ALEXTANGXIAO** [comment]
相同Attribute才可以收到。
